version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Makassar
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Makassar
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci

  - package-ecosystem: gitsubmodule
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Makassar
    open-pull-requests-limit: 3
    labels:
      - dependencies
